name: QuaverLib Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '5.0.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies 
      run: dotnet restore QuaverLibTest/QuaverLibTest.csproj
    - name: Build
      run: dotnet build --no-restore QuaverLibTest/QuaverLibTest.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal QuaverLibTest/QuaverLibTest.csproj
